//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopDongHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public string MaDon { get; set; }
        public string SDT { get; set; }
        public string TenKH { get; set; }
        public string LoaiSP { get; set; }
        public int SoLuong { get; set; }
        public System.DateTime NgayIn { get; set; }
        public string MaNV { get; set; }
    
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
